### ISSUE TITLE
Improve documentation and new user experience

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio-extension-turtlesim#3]
It's not clear what will happen when I install this extension in Foxglove Studio:

<img width="319" alt="image" src="https://user-images.githubusercontent.com/14237/132106376-9460c0c3-3426-413f-9df0-61c0adc86675.png">

If I happen to discover that a new Turtle panel is available, it greets me with a mysterious blue square:

<img width="403" alt="image" src="https://user-images.githubusercontent.com/14237/132106380-e6a9d9d1-0f32-43ba-8777-bdc54719fb26.png">

It would be helpful for the extension documentation to mention that the extension offers a new panel, and to provide (or link to) instructions on how to run turtlesim and see the extension in action.

**Comment by Shapeno** [comment]
I don't understand too.

**Comment by jtbandes** [comment]
Internal tracking issue: https://linear.app/foxglove/issue/FG-4206/turtlesim-extension-is-missing-documentation
